// Typed access to the canonical seed. Every file here is generated by
// scripts/gen_seed.mjs and checked by scripts/validate_seed.mjs; edit the script, not the JSON.
import type {
  BillingAccount, Charge, Container, Contract, CreditMemo, FeeRule, Hauler, Invoice, Party, Payment,
  PaymentAllocation, ProcessorBatch, Quote, RateVersion, Request, Route, ScaleTicket, ServiceCatalog,
  ServiceEvent, ServiceItem, Site, TaxRule, WaivedCharge, WorkOrder, Zone,
} from '../types';
import haulerJson from './hauler.json';
import zonesJson from './zones.json';
import routesJson from './routes.json';
import catalogJson from './catalog.json';
import rateVersionsJson from './rateVersions.json';
import feeRulesJson from './feeRules.json';
import taxRulesJson from './taxRules.json';
import partiesJson from './parties.json';
import accountsJson from './accounts.json';
import sitesJson from './sites.json';
import serviceItemsJson from './serviceItems.json';
import containersJson from './containers.json';
import contractsJson from './contracts.json';
import workOrdersJson from './workOrders.json';
import serviceEventsJson from './serviceEvents.json';
import scaleTicketsJson from './scaleTickets.json';
import chargesJson from './charges.json';
import invoicesJson from './invoices.json';
import paymentsJson from './payments.json';
import allocationsJson from './allocations.json';
import batchesJson from './batches.json';
import creditMemosJson from './creditMemos.json';
import waivedChargesJson from './waivedCharges.json';
import requestsJson from './requests.json';
import quotesJson from './quotes.json';
import addressesJson from './addresses.json';

/** Storefront-only lookup table (see DECISIONS.md). Not part of the shared contract. */
export interface SeedAddress {
  id: string;
  label: string;
  line1: string;
  city: string;
  state: string;
  zip: string;
  zoneId: string;
  routeId?: string;
  franchiseHolder?: string;
  boundaryReason?: string;
}

export const seed = {
  hauler: haulerJson as Hauler,
  zones: zonesJson as Zone[],
  routes: routesJson as Route[],
  catalog: catalogJson as ServiceCatalog[],
  rateVersions: rateVersionsJson as RateVersion[],
  feeRules: feeRulesJson as FeeRule[],
  taxRules: taxRulesJson as TaxRule[],
  parties: partiesJson as Party[],
  accounts: accountsJson as BillingAccount[],
  sites: sitesJson as Site[],
  serviceItems: serviceItemsJson as ServiceItem[],
  containers: containersJson as Container[],
  contracts: contractsJson as Contract[],
  workOrders: workOrdersJson as WorkOrder[],
  serviceEvents: serviceEventsJson as ServiceEvent[],
  scaleTickets: scaleTicketsJson as ScaleTicket[],
  charges: chargesJson as Charge[],
  invoices: invoicesJson as Invoice[],
  payments: paymentsJson as Payment[],
  allocations: allocationsJson as PaymentAllocation[],
  batches: batchesJson as ProcessorBatch[],
  creditMemos: creditMemosJson as CreditMemo[],
  waivedCharges: waivedChargesJson as WaivedCharge[],
  requests: requestsJson as Request[],
  quotes: quotesJson as Quote[],
  addresses: addressesJson as SeedAddress[],
};

export type Seed = typeof seed;

export const seedCounts = {
  zones: seed.zones.length,
  routes: seed.routes.length,
  catalog: seed.catalog.length,
  rateVersions: seed.rateVersions.length,
  accounts: seed.accounts.length,
  quotes: seed.quotes.length,
  addresses: seed.addresses.length,
};
