// One typed seed object keyed by table name. Every JSON file in this directory is imported here.
// The JSON is generated by scripts/gen_seed.mjs and validated by scripts/check_seed.mjs.

import type {
  BillingAccount, Charge, Container, Contract, CreditMemo, FeeRule, Hauler, Invoice, Party, Payment,
  PaymentAllocation, ProcessorBatch, Quote, RateVersion, Request, Route, ScaleTicket, ServiceCatalog,
  ServiceEvent, ServiceItem, Site, TaxRule, WaivedCharge, WorkOrder, Zone,
} from '../types';

import haulerJson from './hauler.json';
import partiesJson from './parties.json';
import accountsJson from './accounts.json';
import sitesJson from './sites.json';
import zonesJson from './zones.json';
import routesJson from './routes.json';
import catalogJson from './catalog.json';
import containersJson from './containers.json';
import serviceItemsJson from './serviceItems.json';
import rateVersionsJson from './rateVersions.json';
import feeRulesJson from './feeRules.json';
import taxRulesJson from './taxRules.json';
import contractsJson from './contracts.json';
import quotesJson from './quotes.json';
import workOrdersJson from './workOrders.json';
import serviceEventsJson from './serviceEvents.json';
import scaleTicketsJson from './scaleTickets.json';
import chargesJson from './charges.json';
import waivedJson from './waived.json';
import invoicesJson from './invoices.json';
import creditMemosJson from './creditMemos.json';
import paymentsJson from './payments.json';
import allocationsJson from './allocations.json';
import batchesJson from './batches.json';
import requestsJson from './requests.json';
import eventRatesJson from './eventRates.json';

export interface Seed {
  hauler: Hauler;
  parties: Party[];
  accounts: BillingAccount[];
  sites: Site[];
  zones: Zone[];
  routes: Route[];
  catalog: ServiceCatalog[];
  containers: Container[];
  serviceItems: ServiceItem[];
  rateVersions: RateVersion[];
  feeRules: FeeRule[];
  taxRules: TaxRule[];
  contracts: Contract[];
  quotes: Quote[];
  workOrders: WorkOrder[];
  serviceEvents: ServiceEvent[];
  scaleTickets: ScaleTicket[];
  charges: Charge[];
  waived: WaivedCharge[];
  invoices: Invoice[];
  creditMemos: CreditMemo[];
  payments: Payment[];
  allocations: PaymentAllocation[];
  batches: ProcessorBatch[];
  requests: Request[];
}

// JSON imports widen string literal unions to string, so each table is asserted to its contract type here.
// scripts/check_seed.mjs validates the literal values so the assertion is honest.
export const seed: Seed = {
  hauler: haulerJson as Hauler,
  parties: partiesJson as Party[],
  accounts: accountsJson as BillingAccount[],
  sites: sitesJson as Site[],
  zones: zonesJson as Zone[],
  routes: routesJson as Route[],
  catalog: catalogJson as ServiceCatalog[],
  containers: containersJson as Container[],
  serviceItems: serviceItemsJson as ServiceItem[],
  rateVersions: rateVersionsJson as RateVersion[],
  feeRules: feeRulesJson as FeeRule[],
  taxRules: taxRulesJson as TaxRule[],
  contracts: contractsJson as Contract[],
  quotes: quotesJson as Quote[],
  workOrders: workOrdersJson as WorkOrder[],
  serviceEvents: serviceEventsJson as ServiceEvent[],
  scaleTickets: scaleTicketsJson as ScaleTicket[],
  charges: chargesJson as Charge[],
  waived: waivedJson as WaivedCharge[],
  invoices: invoicesJson as Invoice[],
  creditMemos: creditMemosJson as CreditMemo[],
  payments: paymentsJson as Payment[],
  allocations: allocationsJson as PaymentAllocation[],
  batches: batchesJson as ProcessorBatch[],
  requests: requestsJson as Request[],
};

/**
 * Exception and event rates in cents (addendum B4 and D5). A rate table, not a contract entity, so it sits beside
 * the seed tables rather than inside Seed. extraPickup is portal-local until shared/ names one (DECISIONS.md).
 */
export interface EventRates {
  extraBags: number;
  overload: number;
  contamination: number;
  dryRun: number;
  extraPickup: number;
}
export const eventRates: EventRates = eventRatesJson as EventRates;

// Seeded ServiceEvent.photoUrl values are relative paths like "photos/blocked-driveway.svg".
// Vite resolves the files under src/seed/photos to served URLs here so the UI can render them
// in dev and in the production build without a public/ copy.
const photoModules = import.meta.glob('./photos/*.svg', { eager: true, query: '?url', import: 'default' }) as Record<string, string>;
export const photoUrls: Record<string, string> = Object.fromEntries(
  Object.entries(photoModules).map(([path, url]) => [path.replace('./', ''), url]),
);

/** Resolve a seeded photoUrl to something an img tag can load. Unknown paths pass through unchanged. */
export function resolvePhoto(photoUrl: string | undefined): string | undefined {
  if (!photoUrl) return undefined;
  return photoUrls[photoUrl] ?? photoUrl;
}
